// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyectos_API.Datos;

#nullable disable

namespace Proyectos_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyectos_API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "#",
                            Detalle = "Detalle de la Villa",
                            FechaActualizacion = new DateTime(2023, 6, 19, 11, 9, 57, 208, DateTimeKind.Local).AddTicks(4156),
                            FechaCreacion = new DateTime(2023, 6, 19, 11, 9, 57, 208, DateTimeKind.Local).AddTicks(4353),
                            ImagenURL = "#",
                            MetrosCuadrados = 5,
                            Nombre = "Villa nueva",
                            Ocupantes = 5,
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "#",
                            Detalle = "Detalle de la Villa",
                            FechaActualizacion = new DateTime(2023, 6, 19, 11, 9, 57, 208, DateTimeKind.Local).AddTicks(4357),
                            FechaCreacion = new DateTime(2023, 6, 19, 11, 9, 57, 208, DateTimeKind.Local).AddTicks(4359),
                            ImagenURL = "#",
                            MetrosCuadrados = 16,
                            Nombre = "Villa real",
                            Ocupantes = 10,
                            Tarifa = 400.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
